### ISSUE TITLE
Every patch is resolving dependencies each time they're ran

### ISSUE THREAD

**Issue by misandrie** [noverd/ArabicaCliento#1]
Computer explodes and its bad okay

**Comment by PetrosanW** [comment]
yes, my computer is booting at 100%%

**Comment by noverd** [comment]
Fixed for a half by https://github.com/noverd/ArabicaCliento/commit/11e08cef6f3a622335d618704c473105ad554018

**Comment by noverd** [comment]
Fixed by https://github.com/noverd/ArabicaCliento/pull/4
